version: "3.1"
services:
    vlc:
        build: vlc
        env_file: .env
        volumes:
            - ./app/entrypoint.php:/app/entrypoint.php
            - ./config/cameras.json:/app/config/cameras.json
            - ./vendor/:/app/vendor
        ports:
            - ${PORTS}
        entrypoint:
            - php
            - /app/entrypoint.php
